### PR TITLE
Filter machine lifecycle events

### LINKED ISSUE #226: Reconciliation of Unmanaged Machines in `Libvirt-Provider`
**Describe the bug**
After integrating support for libvirt events (issue #177), it has been observed that machines not managed by the libvirt provider (i.e., not present in the store) are also triggering requeue requests due to their lifecycle events. The libvirt provider should ideally only reconcile machines that it manages, i.e., machines present in the store.

**To Reproduce**
- Create a machine using the virsh command.
- Start the libvirt provider.
- Destroy the machine created in step 1.
- Observe the requeue request in the libvirt provider console for the machine that was destroyed.

**Expected behavior**
The libvirt provider should only reconcile machines that it manages, i.e., machines present in the store.

**Proposed Solution**
Implement a check in the libvirt provider to ensure that only machines present in the store trigger requeue requests and undergo reconciliation. Any events related to unmanaged machines should be ignored.

**Additional context**
This issue is critical for maintaining the efficiency and performance of the libvirt provider in environments with a mix of managed and unmanaged machines.

### PR DESCRIPTION
**Pull request by lukasfrank**
# Proposed Changes

- Only enqueue events from `Machine`s managed by `libvirt-provider`

Fixes https://github.com/ironcore-dev/libvirt-provider/issues/226

### CODE REVIEW

File: pkg/controllers/machine_controller.go [hunk 1]
```diff
@@ -270,14 +269,24 @@ func (r *MachineReconciler) startEnqueueMachineByLibvirtEvent(ctx context.Contex
...
+			if err != nil {
+				if errors.Is(err, store.ErrNotFound) {
+					log.V(2).Info("Skipped: not managed by libvirt-provider", "machineID", machine.ID)
+					continue
+				}
+				log.Error(err, "failed to fetch machine from store")
+				continue
+			}
+
+			log.V(1).Info("requeue machine", "machineID", machine.ID, "eventID", evt.Event)
```
Comment (lukas016) [inline pkg/controllers/machine_controller.go:288]: eventID isn't very correct. It is more subevent ID in context.
```suggestion
			log.V(1).Info("requeue machine", "machineID", machine.ID, "lifecycleEventID", evt.Event)
```

**Review by lukas016 — CHANGES_REQUESTED** [review]
logging need to be improve

File: pkg/controllers/machine_controller.go (hunk 1 above)
Comment (lukasfrank) [reply pkg/controllers/machine_controller.go]: fixed

**Review by lukas016 — APPROVED** [review]
