### PR TITLE
Handling Empty Files Before Unmarshalling to Prevent Unmarshal Errors

### LINKED ISSUE #155: Handle Empty Files Before Unmarshalling to Prevent Unmarshal Errors
**Describe the bug**
We have several features implemented, such as `startCheckAndEnqueueVolumeResize`, `startCheckAndEnqueueMachineState`, and `startGarbageCollector`, that operate at regular intervals in separate goroutines. These features involve listing machines in the store. However, during the investigation of the inconsistent behavior observed in integration tests, it has been observed that although it is rare, the error `failed to list machines {"error": "failed to read object: failed to unmarshal object: unexpected end of JSON input"}` occurs occasionally.

**Root Cause Analysis**
Upon investigation, it was discovered that this error primarily occurs because the code retrieves a file from the store and attempts to unmarshal it directly without first checking if the file is empty. When the code tries to unmarshal an empty file, the aforementioned error occurs.

**Proposed Solution**
The proposed solution is to implement a check for an empty file before unmarshalling it. If the file is empty, the system should return an empty object instead of attempting to unmarshal it.

**Expected Outcome**
With the implementation of the proposed solution, we anticipate the elimination of the unexpected end of JSON input error. This will enhance the stability and reliability of the system, ensuring consistent behavior during integration tests and regular operations.

### PR DESCRIPTION
**Pull request by so-sahu**
Fixes https://github.com/ironcore-dev/libvirt-provider/issues/155

### CODE REVIEW

File: pkg/host/store.go [hunk 1]
```diff
@@ -221,6 +221,10 @@ func (s *Store[E]) get(id string) (E, error) {
 	}
 
 	obj := s.newFunc()
+	if len(file) == 0 {
```
Comment (lukas016) [inline pkg/host/store.go:224]: i prefer maybe add mutex.Lock for getting of file content

Comment (lukasfrank) [reply pkg/host/store.go:224]: I agree, please use a `RWMutex` in the store.

File: pkg/host/store.go [hunk 2]
```diff
@@ -221,6 +221,10 @@ func (s *Store[E]) get(id string) (E, error) {
...
+		return obj, err
+	}
+
 	if err := json.Unmarshal(file, &obj); err != nil {
 		return utils.Zero[E](), fmt.Errorf("failed to unmarshal object: %w", err)
```
[the remark this answers is not in the document]
Comment (so-sahu) [reply pkg/host/store.go]: Added

File: pkg/host/store.go (hunk 1 above)
Comment (so-sahu) [reply pkg/host/store.go]: Added.

File: pkg/host/store.go [hunk 3]
```diff
@@ -211,6 +211,9 @@ func (s *Store[E]) Watch(ctx context.Context) (store.Watch[E], error) {
 }
 
 func (s *Store[E]) get(id string) (E, error) {
+	s.idMu.RLock(id)
```
Comment (lukas016) [inline pkg/host/store.go:214]: it cannot work. You will create deadlock in update function. In update function you locked mutex for writting so RLock will wait here for unlock of write operation which cannot be done because it will be block RLock function.

File: pkg/sync/sync.go [hunk 4]
```diff
@@ -25,41 +25,69 @@ func NewMutexMap[K comparable]() *MutexMap[K] {
...
-
 	entry.mu.Lock()
+	for entry.readerCnt > 0 {
+		entry.readerDone.Wait()
+	}
 }
 
-// Unlock unlocks the given key.
+// Unlock unlocks the given key for writing.
 func (m *MutexMap[K]) Unlock(key K) {
```
Comment (lukas016) [inline pkg/sync/sync.go:47]: why we cannot use existing solution?

**Review by lukas016 — CHANGES_REQUESTED** [review]

File: pkg/host/store.go (hunk 3 above)
Comment (so-sahu) [reply pkg/host/store.go:214]: No, it won't lead to deadlock. as get will increase the redercount and write will wait for it to complete and then write. I validated it. It's working fine.

It would have led to deadlock in current implementations due to the reason you mentioned.

File: pkg/sync/sync.go (hunk 4 above)
Comment (so-sahu) [reply pkg/sync/sync.go:47]: If we try to use existing solution here, it would lead to deadlock due to the same reason you mentioned. Hence, I have used conditional synchronization..

File: pkg/host/store.go (hunk 3 above)
Comment (lukas016) [reply pkg/host/store.go:214]: but you can create starvation problem in this case, i think. if you will get very quickly new reading operation, write can be postponed forever.

Comment (so-sahu) [reply pkg/host/store.go:214]: In theory, it's possible. However, I haven't encountered such an issue even after running multiple instances of consecutive integration tests, especially considering the already super-fast read operations. Therefore, I believe a client sending GET requests faster than the this might not be a practical scenario.

However, we can always refactor if we see any such situation in real-time in future.

Comment (so-sahu) [reply pkg/host/store.go]: As discussed offline, there's no need to over-engineer in this case. Therefore, proceeding with a simple solution in the latest commit.

File: pkg/sync/sync.go (hunk 4 above)
Comment (so-sahu) [reply pkg/sync/sync.go]: Using the existing solution now.

**Review by lukas016 — APPROVED** [review]
/LGTM

**Review by hardikdr — APPROVED** [review]
Thanks for the PR !! 
Let's keep an eye on how the locks during reads play out. If things get slow, we might want to adjust later.
