### PR TITLE
Fixed `nil pointer` dereference 

### LINKED ISSUE #134: Redundant Assignment and Potential Nil Pointer Dereference in `reconcileDesiredNetworkInterface`
In the `reconcileDesiredNetworkInterface` method, the line `mountedNic.networkInterface.Handle = providerNic.Handle` appears redundant as it is not utilized. This assumes `mountedNic` is non-nil before checking the map element, which may cause a panic.

### PR DESCRIPTION
**Pull request by lukasfrank**
# Proposed Changes

- Fix usage of `mountedNic` before checking existence 

Fixes #134

### CODE REVIEW

**Review by so-sahu — DISMISSED** [review]

File: pkg/controllers/machine_controller_nics.go [hunk 1]
```diff
@@ -216,7 +216,6 @@ func (r *MachineReconciler) reconcileDesiredNetworkInterface(
 	}
 
 	mountedNic, ok := mountedNics[nic.Name]
-	mountedNic.networkInterface.Handle = providerNic.Handle
 	if ok && reflect.DeepEqual(mountedNic.networkInterface, providerNic) {
```
Comment (hardikdr) [inline pkg/controllers/machine_controller_nics.go:219]: Afai remember, this line was added while adapting the controllers to the new APINet resources with Axel, to prevent the DeepEqual from failing. 
This issue emerged as the `.Handle` was newly defined with APINet resource adaptations from the Plugin, but it is not set in the `MountedNic` structure. 
I would recommend testing the flow with this change, and if it's still failing, maybe have a more holistic solution.

**Review by hardikdr — APPROVED** [review]

File: pkg/controllers/machine_controller_nics.go (hunk 1 above)
Comment (hardikdr) [reply pkg/controllers/machine_controller_nics.go]: Sure, thanks.
